%{?!ros_distro:%global ros_distro rolling}
%global pkg_name tango_icons_vendor
%global normalized_pkg_name %{lua:return (string.gsub(rpm.expand('%{pkg_name}'), '_', '-'))}

Name:           ros-rolling-tango-icons-vendor
Version:        0.5.1
Release:        2%{?dist}
Summary:        ROS %{pkg_name} package

License:        Apache License 2.0 and Public Domain
URL:            http://ros.org/wiki/qt_gui_icons
Source0:        %{name}-%{version}.tar.gz

BuildRequires:  bloom-rpm-macros
BuildRequires:  cmake

%{?bloom_package}

%description
tango_icons_vendor provides the public domain Tango icons for non-linux systems
(Tango Icon Library) from the Tango Desktop Project


%package devel
Release:        %{release}%{?release_suffix}
Summary:        %{summary}
Provides:       %{name} = %{version}-%{release}
Provides:       %{name}%{?_isa} = %{version}-%{release}
Requires:       %{name}-runtime%{?_isa} = %{version}-%{release}

%description devel
tango_icons_vendor provides the public domain Tango icons for non-linux systems
(Tango Icon Library) from the Tango Desktop Project


%package runtime
Release:        %{release}
Summary:        %{summary}

%description runtime
tango_icons_vendor provides the public domain Tango icons for non-linux systems
(Tango Icon Library) from the Tango Desktop Project


%prep
%autosetup -p1


%generate_buildrequires
%bloom_buildrequires


%build
%cmake \
    -UINCLUDE_INSTALL_DIR \
    -ULIB_INSTALL_DIR \
    -USYSCONF_INSTALL_DIR \
    -USHARE_INSTALL_PREFIX \
    -ULIB_SUFFIX \
    -DCMAKE_INSTALL_PREFIX="%{bloom_prefix}" \
    -DAMENT_PREFIX_PATH="%{bloom_prefix}" \
    -DCMAKE_PREFIX_PATH="%{bloom_prefix}" \
    -DSETUPTOOLS_DEB_LAYOUT=OFF \
%if !0%{?with_tests}
    -DBUILD_TESTING=OFF \
%endif

%cmake3_build


%install
%cmake_install


%if 0%{?with_tests}
%check
# Look for a Makefile target with a name indicating that it runs tests
TEST_TARGET=$(%__make -qp -C %{__cmake_builddir} | sed "s/^\(test\|check\):.*/\\1/;t f;d;:f;q0")
if [ -n "$TEST_TARGET" ]; then
CTEST_OUTPUT_ON_FAILURE=1 \
    %cmake_build $TEST_TARGET || echo "RPM TESTS FAILED"
else echo "RPM TESTS SKIPPED"; fi
%endif


%files devel
%dir %{bloom_prefix}
%ghost %{bloom_prefix}/share/%{pkg_name}/package.xml


%files runtime
%{bloom_prefix}


%changelog
* Tue Apr 28 2026 Scott K Logan <scott@openrobotics.org> - 0.5.1-2
- Autogenerated by Bloom

* Tue Apr 21 2026 Scott K Logan <scott@openrobotics.org> - 0.5.1-1
- Autogenerated by Bloom
